name: Say hello

on:
  push:
    branches:
      - main

jobs:
  hello_world:
    runs-on: ubuntu-latest
    steps:
      - name: Echo the message
        run: |
          echo "Hola midu!"
      - name: Echoe the message
        run: |
          echo "Hello Pablo!"
      - name: Dime la fecha
      run: date
      - name: Dime la hora
      run: time
      