name: Deployment pipeline
on:
    push:
      branches:
        - main
 
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          
      - name: Deploy the code
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install dependencies
        run: npm install
        
      - name: mostrar
        run: pwd
         